[phases.setup]
nixPkgs = ["chromium", "chromedriver", "python39", "python39Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "gunicorn app:app" 