services:
  - type: web
    name: zalo-ai-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: GEMINI_API_KEY
        sync: false 